### ISSUE TITLE
[BUG] NoMethodError

### ISSUE THREAD

**Issue by BenjaRubio** [lothardp/ProyectoTesting#1]
Al crear un barco, la línea
@stern = is_vertical ? { "row" => (row + size - 1), "col" => col } : { "row" =>  row, "col" => (col + size - 1) }
arroja error al sumar row y size

Traceback (most recent call last):
        3: from main.rb:26:in `<main>'
        2: from /mnt/c/Users/Benja Rubio/Desktop/UC/Testing/ProyectoTesting/lib/one_player_controller.rb:25:in `request_ships'
        1: from /mnt/c/Users/Benja Rubio/Desktop/UC/Testing/ProyectoTesting/lib/one_player_controller.rb:25:in `new'
/mnt/c/Users/Benja Rubio/Desktop/UC/Testing/ProyectoTesting/lib/ship.rb:9:in `initialize': undefined method `+' for nil:NilClass (NoMethodError)

**Comment by lothardp** [comment]
Esto ya no es un problema, se cambió ese código.
